# Generated by Django 2.2.4 on 2019-09-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alter_ego',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
